export default {
  products: [
    {
      id: 1,
      image: "/images/download1.jpg",
      category: "Shirts",
      name: "Slim Shirt",
      brand: "Polo",
      price: 1200,
      rating: 4.5,
      reviews: 10,
      status: 1,
    },
    {
      id: 2,
      image: "/images/download1.jpg",
      category: "Shirts",
      name: "best Shirt",
      brand: "Polo",
      price: 1200,
      rating: 4.5,
      reviews: 10,
      status: 1,
    },
    {
      id: 3,
      image: "/images/download1.jpg",
      category: "Shirts",
      name: "good Shirt",
      brand: "Polo",
      price: 1200,
      rating: 4.5,
      reviews: 10,
      status: 1,
    },
    {
      id: 4,
      image: "/images/download1.jpg",
      category: "Shirts",
      name: "nice Shirt",
      brand: "Polo",
      price: 1200,
      rating: 4.5,
      reviews: 10,
      status: 1,
    },
    {
      id: 5,
      image: "/images/download1.jpg",
      category: "Shirts",
      name: "kamal Shirt",
      brand: "Polo",
      price: 1200,
      rating: 4.5,
      reviews: 10,
      status: 1,
    },
    {
      id: 6,
      image: "/images/download1.jpg",
      category: "Shirts",
      name: "heavy Shirt",
      brand: "Polo",
      price: 1200,
      rating: 4.5,
      reviews: 10,
      status: 1,
    },
  ],
};
